eiuser/accounts/urls.py
from django.urls import path

from .views import (
    ActivationView,
    ActivationDoneView,
    ActivationConfirmView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    SignupDoneView,
)

app_name = 'accounts'

# signup endpoints
urlpatterns = [path('signup/done/', SignupDoneView.as_view(), name='signup_done')]

# account activation endpoints
urlpatterns += [
    path('activation/', ActivationView.as_view(), name='activation'),
    path('activation/done/', ActivationDoneView.as_view(), name='activation_done'),
    path('activation/<uidb64>/<token>/', ActivationConfirmView.as_view(), name='activation_confirm'),
]

# password change endpoints
urlpatterns += [
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
]

# password reset endpoints
urlpatterns += [
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

eiuser/eiuser/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import HomeView, LoginView, LogoutView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('home/', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
]

eiuser/accounts/models.py
import uuid

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    uuid = models.UUIDField(_('UUID'), default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(_('name'), max_length=64)
    email = models.EmailField(_('email address'), unique=True)
    created_at = models.DateTimeField(_('creation time'), auto_now_add=True)
    activated_at = models.DateTimeField(_('activation time'), null=True, blank=True)
    agreed_to_tnc_at = models.DateTimeField(_('T&C agreement time'), null=True, blank=True)
    is_active = models.BooleanField(_('active'), default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        swappable = 'AUTH_USER_MODEL'

eiuser/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    PasswordChangeForm as BasePasswordChangeForm,
    PasswordResetForm as BasePasswordResetForm,
    SetPasswordForm as BaseSetPasswordForm,
    UserCreationForm as BaseUserCreationForm,
    UserChangeForm as BaseUserChangeForm,
)
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from . import services

UserModel = get_user_model()


class UserCreationForm(BaseUserCreationForm):
    agree_to_tnc = forms.BooleanField(label=_('Accept our terms of use'), required=False)

    class Meta(BaseUserCreationForm.Meta):
        model = UserModel
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = None
        self.fields['password2'].label = _('Confirm password')
        self.fields['password2'].help_text = None

    def clean_agree_to_tnc(self):
        is_agreed_to = self.cleaned_data['agree_to_tnc']
        if not is_agreed_to:
            raise ValidationError(_('It is required that you agree to the terms of use.'), code='invalid')
        return is_agreed_to

    def save(self, commit=True, send_activation_email=True):
        user = super().save(commit=False)
        user.agreed_to_tnc_at = timezone.now()
        if commit:
            user.save()
        if send_activation_email:
            services.send_activation_email(user)
        return user


class AdminUserCreationForm(UserCreationForm):
    agree_to_tnc = None


class UserChangeForm(BaseUserChangeForm):
    class Meta(BaseUserChangeForm.Meta):
        model = UserModel
        fields = [
            'name',
            'email',
            'is_active',
            'is_staff',
            'is_superuser',
            'groups',
            'user_permissions',
        ]


class ActivationForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )
    password = forms.CharField(
        label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    def clean(self):
        validated_data = super().clean()
        try:
            user = UserModel.objects.get(email=validated_data['email'])
        except UserModel.DoesNotExist:
            raise self.get_validation_error()

        if not user.check_password(validated_data['password']):
            raise self.get_validation_error()

        return validated_data

    def get_validation_error(self):
        return ValidationError(
            _('Please enter a correct email address and password. Note that both fields may be case-sensitive.'),
            code='invalid',
        )


class PasswordChangeForm(BasePasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].help_text = None
        self.fields['new_password2'].label = _('Confirm new password')


class PasswordResetForm(BasePasswordResetForm):
    subject_template_name = 'accounts/email/password_reset_subject.txt'
    email_template_name = 'accounts/email/password_reset_body.txt'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = _('Email address')

    def save(
        self,
        domain_override=None,
        subject_template_name=None,
        email_template_name=None,
        use_https=False,
        token_generator=None,
        from_email=None,
        request=None,
        html_email_template_name=None,
        extra_email_context=None,
    ):
        return super().save(
            domain_override=domain_override,
            subject_template_name=subject_template_name or self.subject_template_name,
            email_template_name=email_template_name or self.email_template_name,
            use_https=use_https,
            token_generator=token_generator,
            from_email=from_email,
            request=request,
            html_email_template_name=html_email_template_name,
            extra_email_context=extra_email_context,
        )


class SetPasswordForm(BaseSetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].help_text = None
        self.fields['new_password2'].label = _('Confirm new password')

eiuser/accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    LogoutView as BaseLogoutView,
    PasswordChangeView as BasePasswordChangeView,
    PasswordChangeDoneView as BasePasswordChangeDoneView,
    PasswordResetCompleteView as BasePasswordResetCompleteView,
    PasswordResetConfirmView as BasePasswordResetConfirmView,
    PasswordResetView as BasePasswordResetView,
    PasswordResetDoneView as BasePasswordResetDoneView,
)
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView

from . import services
from .tokens import account_activation_token_generator
from .forms import ActivationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm, UserCreationForm

UserModel = get_user_model()


class SignupView(CreateView):
    form_class = UserCreationForm
    model = UserModel
    success_url = reverse_lazy('accounts:signup_done')
    template_name = 'accounts/signup.html'

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SignupDoneView(TemplateView):
    template_name = 'accounts/signup_done.html'


class ActivationView(FormView):
    form_class = ActivationForm
    success_url = reverse_lazy('accounts:activation_done')
    template_name = 'accounts/activation.html'

    @method_decorator(csrf_protect)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        email = UserModel.objects.normalize_email(form.cleaned_data['email'])

        try:
            user = UserModel.objects.get(email=email)
            if user.activated_at is None and user.check_password(form.cleaned_data['password']):
                services.send_activation_email(user)
        except UserModel.DoesNotExist:
            pass

        return super().form_valid(form)


class ActivationDoneView(TemplateView):
    template_name = 'accounts/activation_done.html'


class ActivationConfirmView(DetailView):
    _has_token_check_failed = False
    model = UserModel
    pk_url_kwarg = 'uidb64'

    def setup(self, request, *args, **kwargs):
        kwargs[self.pk_url_kwarg] = force_str(urlsafe_base64_decode(kwargs[self.pk_url_kwarg]))
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        user = super().get_object(queryset)

        if not account_activation_token_generator.check_token(user, self.kwargs['token']):
            self._has_token_check_failed = True
            return user

        user.is_active = True
        user.activated_at = timezone.now()
        user.save()
        return user

    def get_template_names(self):
        if self._has_token_check_failed:
            return ['accounts/activation_confirm_failed.html']
        return ['accounts/activation_confirm.html']


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/home.html'


class LoginView(BaseLoginView):
    template_name = 'accounts/login.html'


class LogoutView(BaseLogoutView):
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        messages.info(self.request, _('You\'ve just logged out of your account.'), extra_tags='logout')

        return super().dispatch(request, *args, **kwargs)


class PasswordChangeView(BasePasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'

    def form_valid(self, form):
        messages.info(self.request, _('You\'ve just changed your password.'), extra_tags='password_change')
        return super().form_valid(form)


class PasswordChangeDoneView(BasePasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'


class PasswordResetView(BasePasswordResetView):
    email_template_name = 'accounts/email/password_reset_email.txt'
    form_class = PasswordResetForm
    subject_template_name = 'accounts/email/password_reset_subject.txt'
    success_url = reverse_lazy('accounts:password_reset_done')
    template_name = 'accounts/password_reset.html'

    def form_valid(self, form):
        messages.info(
            self.request,
            _('We\'ve sent you an email containing instructions for resetting your password.'),
            extra_tags='password_reset',
        )
        return super().form_valid(form)


class PasswordResetDoneView(BasePasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(BasePasswordResetConfirmView):
    form_class = SetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'

    def form_valid(self, form):
        messages.info(
            self.request,
            _('You\'ve successfully reset your password. You may now go ahead and log in.'),
            extra_tags='password_reset_confirm',
        )
        return super().form_valid(form)


class PasswordResetCompleteView(BasePasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

eiuser/accounts/templates/accounts/activation.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'request account activation link' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h4 text-muted mb-4">{% translate 'Account activation link request' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method="post" action="">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Send me an activation link' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/activation_confirm.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block title %}
  {{ request.site.name }} - {% translate 'account successfully activated' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <p>{% translate 'You have successfully activated your account!' %}</p>
        <p>{% translate 'Please click on the button below to log in to your brand new account.' %}</p>
        <div class="pt-2">
          <a href='{% url "login" %}' class="btn btn-primary px-4">{% translate 'Login' %}</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/activation_confirm_failed.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block title %}
  {{ request.site.name }} - {% translate 'account activation failed' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <h1 class="h4 text-muted mb-3">{% translate 'Activation Failed' %}</h1>
        <p>{% translate 'Oops, this activation link is either invalid or has expired.' %}</p>

        <p>{% translate 'Please click on the button below to request a new activation link.' %}</p>

        <div class="py-2">
          <a href="{% url 'accounts:activation' %}" class="btn btn-primary px-4">{% translate 'Request new activation link' %}</a>
        </div>

        {% url 'login' as login_url %}
        <p><small>{% blocktranslate %}Not sure whether your account is in need of activation? Please <a href="{{ login_url }}">try logging in</a> to check.{% endblocktranslate %}</small></p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/activation_done.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block title %}
  {{ request.site.name }} - {% translate 'account activation link sent' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <p>{% translate 'We have just sent to your email address a link with which you can activate your account.' %}</p>

        <p>{% translate 'This email may take up to fifteen minutes to get to you. So, please wait for it, if it has not yet arrived &mdash; and also check your spam while at it.' %}</p>

        <p>{% translate 'If the email does not arrive after fifteen minutes, please click on the button below to request a new activation link.' %}</p>

        <div class="pt-2">
          <a href='{% url "accounts:activation" %}' class="btn btn-primary px-4">{% translate 'Request new activation link' %}</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/home.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block title %}
  {{ request.site.name }}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="h2 text-muted mb-4">{% translate 'Home' %}</h1>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/login.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'log in to your account' %}
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'registration/css/login.css' %}">
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        {% if 'logout' in message.tags.split %}
          <div class="alert alert-info alert-dismissible fade show mb-4" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Log in to your Account' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Log in' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_change.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'change your password' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Change your password' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Change password' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_change_done.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'password successfully changed' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="h2 text-muted mb-4">{% translate 'Password Change Done' %}</h1>
    {% if messages %}
      {% for message in messages %}
        {% if 'password_change' in message.tags.split %}
          <div class="alert alert-info alert-dismissible fade show mb-4" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_reset.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'request a password reset link' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Password reset' %}</h1>
    <div class="text-center text-muted mb-4">
      <p class="mb-2">{% translate 'Forgotten your password?' %}</p>
      <p>{% translate 'Enter your email address below, and we will email you instructions for setting a new one.' %}</p>
    </div>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Send me password reset instructions' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_reset_complete.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'password successfully reset' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">

    <h1 class="h2 text-muted mb-4">{% translate 'Password Reset Complete' %}</h1>

    {% if messages %}
      {% for message in messages %}
        {% if 'password_reset_confirm' in message.tags.split %}
          <div class="alert alert-info alert-dismissible fade show mb-4" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}

    <p><a href="{% url 'login' %}">{% translate 'Log in with your new password' %}</a></p>

  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_reset_confirm.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'reset your password' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h4 text-muted mb-4">{% translate 'Password Reset' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method="post" action="">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Reset my password' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/password_reset_done.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'password reset link sent' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">

    <h1 class="h2 text-muted mb-4">{% translate 'Password Reset' %}</h1>

    {% if messages %}
      {% for message in messages %}
        {% if 'password_reset' in message.tags.split %}
          <div class="alert alert-info alert-dismissible fade show mb-4" role="alert">
            {{ message | safe }}
            <button type="button" class="close" data-dismiss="alert" aria-label="{% translate 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}

    <div class="alert alert-secondary mb-4" role="alert">{% blocktranslate %}Please note that you will receive the password reset instructions <strong>ONLY IF</strong> you entered the email address you registered your account with into the password reset form.{% endblocktranslate %}</div>

    <p>{% translate 'This email may take up to fifteen minutes to get to you. So, please wait for it if it has not yet arrived. Also, please check your spam folder while waiting.' %}</p>

  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/signup.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {{ request.site.name }} - {% translate 'sign up for an account' %}
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/signup.css' %}">
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <h1 class="text-center h2 text-muted mb-4">{% translate 'Create Your Account' %}</h1>
    <div class="row justify-content-center">
      <div class="col col-sm-11 col-md-9 col-lg-7 col-xl-5">
        <div class="card p-3 pt-4">
          <form method='post' action=''>
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center mt-4">
              <input class="btn btn-primary px-5" type="submit" value="{% translate 'Sign up' %}">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

eiuser/accounts/templates/accounts/signup_done.html
{% extends 'site_base.html' %}

{% load i18n %}
{% block title %}
  {{ request.site.name }} - {% translate 'signup successful' %}
{% endblock %}

{% block main %}
<section class="py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <p>{% blocktranslate with site_name=request.site.name %}Welcome to {{ site_name }}{% endblocktranslate %}</p>

        <p>{% translate 'Please activate your account using the link we have just sent to your email address.' %}</p>

        <p>{% translate 'The email containing the link may take up to fifteen minutes to get to you. So, please wait for it, if it has not yet arrived &mdash; and also check your spam while at it.' %}</p>

        <p>{% translate 'If the email does not arrive after fifteen minutes, please click on the button below to request a new activation link.' %}</p>

        <div class="pt-2">
          <a href='{% url "accounts:activation" %}' class="btn btn-primary px-4">{% translate 'Request new activation link' %}</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}